name: Test and Deploy

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

#      - name: Test
#        run: make jenkins_test

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:latest, ${{ secrets.DOCKER_REPO }}:${GITHUB_SHA::8}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [ docker ]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{}"